# Generated by Django 5.0.3 on 2024-03-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='createad_at',
            new_name='created_at',
        ),
    ]
